<?xml version="1.0"?>
<!-- Sirius differential drive robot URDF -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sirius_robot">
  
  <!-- Robot prefix parameter for frame naming -->
  <xacro:arg name="prefix" default=""/>
  <xacro:property name="prefix" value="$(arg prefix)"/>
  
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="2.0"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_length" value="0.6"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="wheel_mass" value="0.8"/>
  <xacro:property name="wheel_radius" value="0.12"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_ygap" value="0.2"/>
  <xacro:property name="caster_radius" value="0.06"/>

  <!-- Define materials -->
  <material name="sirius_blue">
    <color rgba="0.1 0.3 0.8 1"/>
  </material>
  
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  
  <material name="gray">
    <color rgba="0.8 0.8 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="sirius_blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}"
        iyz="0.0"
        izz="${base_mass / 12.0 * (base_length*base_length + base_width*base_width)}"/>
    </inertial>
  </link>

  <!-- Base Footprint -->
  <link name="${prefix}base_footprint"/>

  <joint name="${prefix}base_joint" type="fixed">
    <parent link="${prefix}base_footprint"/>
    <child link="${prefix}base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Left Wheel -->
  <link name="${prefix}left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <inertia
        ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        iyz="0.0"
        izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
    </inertial>
  </link>

  <joint name="${prefix}left_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}left_wheel"/>
    <origin xyz="0 ${wheel_ygap} ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right Wheel -->
  <link name="${prefix}right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <inertia
        ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
        iyz="0.0"
        izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
    </inertial>
  </link>

  <joint name="${prefix}right_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}right_wheel"/>
    <origin xyz="0 ${-wheel_ygap} ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Front Caster Wheel -->
  <link name="${prefix}front_caster">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${0.1 * 2.0/5.0 * caster_radius*caster_radius}"
        ixy="0.0"
        ixz="0.0"
        iyy="${0.1 * 2.0/5.0 * caster_radius*caster_radius}"
        iyz="0.0"
        izz="${0.1 * 2.0/5.0 * caster_radius*caster_radius}"/>
    </inertial>
  </link>

  <joint name="${prefix}front_caster_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}front_caster"/>
    <origin xyz="${base_length/2 - caster_radius} 0 ${-base_height/2 - caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Rear Caster Wheel -->
  <link name="${prefix}rear_caster">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${0.1 * 2.0/5.0 * caster_radius*caster_radius}"
        ixy="0.0"
        ixz="0.0"
        iyy="${0.1 * 2.0/5.0 * caster_radius*caster_radius}"
        iyz="0.0"
        izz="${0.1 * 2.0/5.0 * caster_radius*caster_radius}"/>
    </inertial>
  </link>

  <joint name="${prefix}rear_caster_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}rear_caster"/>
    <origin xyz="${-base_length/2 + caster_radius} 0 ${-base_height/2 - caster_radius}" rpy="0 0 0"/>
  </joint>

</robot>
