<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sirius3">

  <!-- パラメータ定義 -->
  <xacro:property name="wheel_separation" value="0.362" />
  <xacro:property name="wheel_radius" value="0.0825" />
  <xacro:property name="wheel_width" value="0.041" />
  <xacro:property name="wheel_mass" value="26.68" />
  <xacro:property name="base_mass" value="55.93" />

  <!-- パッケージパス -->
  <xacro:property name="package_name" value="sirius_description" />
  <xacro:property name="mesh_path" value="package://$(arg package_name)/urdf/meshes" />

  <!-- 引数 -->
  <xacro:arg name="package_name" default="sirius_description" />
  <xacro:arg name="use_sim_time" default="true" />
  <xacro:arg name="prefix" default="sirius3/" />

  <!-- マテリアル定義 -->
  <material name="base_blue">
    <color rgba="0.1 0.3 0.6 1.0"/>
  </material>

  <material name="wheel_gray">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>

  <material name="lidar_gray">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <!-- ベースフットプリント（地面接触点の仮想リンク） -->
  <link name="$(arg prefix)base_footprint">
    <!-- 空のリンク -->
  </link>

  <!-- ベースリンク -->
  <link name="$(arg prefix)base_link">
    <inertial>
      <origin xyz="0.0002947164165949161 0.09943035225547472 0.3230235286090794" rpy="0.0 0.0 0.0" />
      <mass value="${base_mass}" />
      <inertia ixx="2.8808637737854497" iyy="2.45977163019146" izz="2.1448545974410616" 
               ixy="0.0009823142017673183" iyz="0.26295068207749944" ixz="-0.003430118472896634" />
    </inertial>
    <visual name="base_link_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <mesh filename="${mesh_path}/Sirius3-body-v2.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="base_blue" />
    </visual>
    <collision name="base_link_collision">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <mesh filename="${mesh_path}/Sirius3-body-v2.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>
  </link>

  <!-- フットプリントとベースを接続するジョイント -->
  <joint name="$(arg prefix)footprint_to_base" type="fixed">
    <parent link="$(arg prefix)base_footprint"/>
    <child link="$(arg prefix)base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ホイールマクロ定義 -->
  <xacro:macro name="wheel" params="prefix side reflect mesh_file wheel_mass_value wheel_inertia_ixx wheel_inertia_iyy wheel_inertia_izz wheel_inertia_ixy wheel_inertia_iyz wheel_inertia_ixz wheel_inertial_origin wheel_visual_origin wheel_visual_rpy joint_origin joint_rpy axis_xyz">
    <link name="$(arg prefix)${side}_wheel">
      <inertial>
        <origin xyz="${wheel_inertial_origin}" rpy="0.0 0.0 0.0" />
        <mass value="${wheel_mass_value}" />
        <inertia ixx="${wheel_inertia_ixx}" iyy="${wheel_inertia_iyy}" izz="${wheel_inertia_izz}" 
                 ixy="${wheel_inertia_ixy}" iyz="${wheel_inertia_iyz}" ixz="${wheel_inertia_ixz}" />
      </inertial>
      <visual name="${side}_wheel_visual">
        <origin xyz="${wheel_visual_origin}" rpy="${wheel_visual_rpy}" />
        <geometry>
          <mesh filename="${mesh_path}/${mesh_file}" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="wheel_gray" />
      </visual>
      <collision name="${side}_wheel_collision">
        <origin xyz="${wheel_visual_origin}" rpy="${wheel_visual_rpy}" />
        <geometry>
          <mesh filename="${mesh_path}/${mesh_file}" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>

    <joint name="${side}_wheel_joint" type="continuous">
      <origin xyz="${joint_origin}" rpy="${joint_rpy}" />
      <parent link="$(arg prefix)base_link" />
      <child link="$(arg prefix)${side}_wheel" />
      <axis xyz="${axis_xyz}" />
      <limit effort="100" velocity="100" />
      <dynamics damping="5.0" friction="2.0" />
    </joint>
  </xacro:macro>

  <!-- 左ホイール -->
  <xacro:wheel 
    prefix="$(arg prefix)"
    side="left" 
    reflect="1"
    mesh_file="Left-Wheel-v1.stl"
    wheel_mass_value="26.684250609189966"
    wheel_inertia_ixx="0.24147472596060576"
    wheel_inertia_iyy="0.13040791997952456"
    wheel_inertia_izz="0.13041983338763752"
    wheel_inertia_ixy="-1.3386522533795057e-05"
    wheel_inertia_iyz="1.9456112928556427e-05"
    wheel_inertia_ixz="-5.293518847815378e-06"
    wheel_inertial_origin="0.00025571114010551453 -0.02153522228931916 -0.0003576198248327911"
    wheel_visual_origin="0.00026615125671401783 0.019999997439497593 -0.0003525390265766926"
    wheel_visual_rpy="-1.5707963267948966 -1.5265566588595898e-16 -1.5707963267948966"
    joint_origin="0.0 0.16 0.13"
    joint_rpy="1.5707963267948968 -1.5707963267948966 0"
    axis_xyz="0.0 -1.0 0.0"
  />

  <!-- 右ホイール -->
  <xacro:wheel 
    prefix="$(arg prefix)"
    side="right" 
    reflect="-1"
    mesh_file="Right-Wheel-v1.stl"
    wheel_mass_value="26.684250609189966"
    wheel_inertia_ixx="0.24147472596060576"
    wheel_inertia_iyy="0.13040791997952456"
    wheel_inertia_izz="0.13041983338763752"
    wheel_inertia_ixy="-1.3386522533795057e-05"
    wheel_inertia_iyz="1.9456112928556427e-05"
    wheel_inertia_ixz="-5.293518847815378e-06"
    wheel_inertial_origin="0.00025571114010551453 -0.02153522228931916 -0.0003576198248327911"
    wheel_visual_origin="0.00026615125671401783 -0.019999997439497593 -0.0003525390265766926"
    wheel_visual_rpy="1.5707963267948966 1.5265566588595898e-16 1.5707963267948966"
    joint_origin="0.0 -0.16 0.13"
    joint_rpy="-1.5707963267948968 -1.5707963267948966 0"
    axis_xyz="0.0 1.0 0.0"
  />

  <!-- LiDAR Link -->
  <link name="$(arg prefix)lidar_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <mass value="0.5" />
      <inertia ixx="0.01" iyy="0.01" izz="0.01" 
               ixy="0.0" iyz="0.0" ixz="0.0" />
    </inertial>
    <visual name="lidar_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="0.052" length="0.072" />
      </geometry>
      <material name="lidar_gray" />
    </visual>
    <collision name="lidar_collision">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="0.052" length="0.072" />
      </geometry>
    </collision>
  </link>

  <!-- LiDAR Joint -->
  <joint name="$(arg prefix)lidar_joint" type="fixed">
    <origin xyz="0.0 0.0 0.85" rpy="0.0 0.0 0.0" />
    <parent link="$(arg prefix)base_link" />
    <child link="$(arg prefix)lidar_link" />
  </joint>

  <!-- Gazebo関連の設定 -->
  <gazebo reference="$(arg prefix)base_link">
    <material>Gazebo/Blue</material>
    <mu1>0.5</mu1>
    <mu2>0.8</mu2>
  </gazebo>

  <gazebo reference="$(arg prefix)left_wheel">
    <material>Gazebo/Grey</material>
    <mu1>1.5</mu1>
    <mu2>1.5</mu2>
  </gazebo>

  <gazebo reference="$(arg prefix)right_wheel">
    <material>Gazebo/Grey</material>
    <mu1>1.5</mu1>
    <mu2>1.5</mu2>
  </gazebo>

  <gazebo reference="$(arg prefix)lidar_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Gazebo Plugins -->
  <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/sirius3</namespace>
        <argument>--ros-args --remap cmd_vel:=cmd_vel</argument>
        <argument>--ros-args --remap odom:=odom</argument>
      </ros>

      <!-- ジョイント名 -->
      <left_joint>$(arg prefix)left_wheel_joint</left_joint>
      <right_joint>$(arg prefix)right_wheel_joint</right_joint>

      <!-- 車輪パラメータ -->
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <!-- コマンド入力トピック -->
      <command_topic>cmd_vel</command_topic>

      <!-- オドメトリ -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>$(arg prefix)base_footprint</robot_base_frame>

      <!-- 更新頻度 -->
      <update_rate>50</update_rate>

      <!-- 最大速度 -->
      <max_wheel_torque>100</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- オドメトリノイズ -->
      <odometry_source>world</odometry_source>
    </plugin>
  </gazebo>

  <!-- LiDAR Sensor Plugin -->
  <gazebo reference="$(arg prefix)lidar_link">
    <sensor type="gpu_ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>100.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/sirius3</namespace>
          <argument>--ros-args --remap ~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>$(arg prefix)lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint State Publisher -->
  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>/sirius3</namespace>
        <argument>--ros-args --remap joint_states:=joint_states</argument>
      </ros>
      <update_rate>50</update_rate>
      <joint_name>$(arg prefix)left_wheel_joint</joint_name>
      <joint_name>$(arg prefix)right_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>
